name: Django

on:
  push:
    paths:
      - django_app/**
      - Makefile
      - .github/**
    branches:
      - 'main'
      - 'feature/**'
      - 'chore/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'develop'
      - 'dependabot/**'
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  DEV_MODE: true
  ELASTIC__HOST: elasticsearch
  ELASTIC__VERSION: 8.11.0
  ELASTIC__USER: elastic
  ELASTIC__PASSWORD: redboxpass
  ELASTIC__PORT: 9200
  ELASTIC__SCHEME: http
  KIBANA_SYSTEM_PASSWORD: redboxpass
  METRICBEAT_INTERNAL_PASSWORD: redboxpass
  FILEBEAT_INTERNAL_PASSWORD: redboxpass
  HEARTBEAT_INTERNAL_PASSWORD: redboxpass
  MONITORING_INTERNAL_PASSWORD: redboxpass
  BEATS_SYSTEM_PASSWORD: redboxpass
  EMBEDDING_MODEL: paraphrase-albert-small-v2
  EMBED_QUEUE_NAME: redbox-embedder-queue
  INGEST_QUEUE_NAME: redbox-ingester-queue
  REDIS_HOST: redis
  REDIS_PORT: 6379
  MINIO_HOST: minio
  MINIO_PORT: 9000
  AWS_ACCESS_KEY: minioadmin
  AWS_SECRET_KEY: minioadmin
  AWS_REGION: eu-west-2
  OBJECT_STORE: minio
  BUCKET_NAME: redbox-storage-dev
  DJANGO_SETTINGS_MODULE: redbox_app.settings
  DEBUG: True
  DJANGO_SECRET_KEY: 1n53cur3K3y
  DJANGO_LOG_LEVEL: WARNING
  ENVIRONMENT: LOCAL
  POSTGRES_USER: redbox-core
  POSTGRES_DB: redbox-core
  POSTGRES_PASSWORD: insecure
  CONTACT_EMAIL: redbox-copilot@cabinetoffice.gov.uk
  POSTGRES_HOST: db
  CORE_API_HOST: testserver
  CORE_API_PORT: 5002
  EMAIL_BACKEND_TYPE: CONSOLE
  GOV_NOTIFY_API_KEY: f4k3_k3y
  FROM_EMAIL: test@example.com
  GOVUK_NOTIFY_PLAIN_EMAIL_TEMPLATE_ID: example-id
  EMAIL_FILE_PATH: '/app/mail'
  USE_STREAMING: False
  COMPRESSION_ENABLED: False

jobs:

  check_migrations:
    name: Check migrations

    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Run migrations
        run: |
          make check-migrations

  run_tests:
    name: Run tests

    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Run tests
        run: |
          make test-django
