# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Integration Tests

on:
  # weekday mealtimes
  schedule:
    - cron: '0 6,12,18 * * 1-5'
  # or on-demand
  workflow_dispatch:

env: 
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  DEV_MODE: true
  ELASTIC__HOST: elasticsearch
  ELASTIC__VERSION: 8.11.0
  ELASTIC__USER: elastic
  ELASTIC__PASSWORD: redboxpass
  ELASTIC__PORT: 9200
  ELASTIC__SCHEME: http
  ELASTIC__SUBSCRIPTION_LEVEL: basic
  KIBANA_SYSTEM_PASSWORD: redboxpass
  METRICBEAT_INTERNAL_PASSWORD: redboxpass
  FILEBEAT_INTERNAL_PASSWORD: redboxpass
  HEARTBEAT_INTERNAL_PASSWORD: redboxpass
  MONITORING_INTERNAL_PASSWORD: redboxpass
  BEATS_SYSTEM_PASSWORD: redboxpass
  EMBEDDING_MODEL: paraphrase-albert-small-v2
  EMBED_QUEUE_NAME: redbox-embedder-queue
  INGEST_QUEUE_NAME: redbox-ingester-queue
  REDIS_HOST: redis
  REDIS_PORT: 6379
  MINIO_HOST: minio
  MINIO_PORT: 9000
  AWS_ACCESS_KEY: minioadmin
  AWS_SECRET_KEY: minioadmin
  AWS_REGION: eu-west-2
  OBJECT_STORE: minio
  BUCKET_NAME: redbox-storage-dev
  DEBUG: True
  DJANGO_SETTINGS_MODULE: redbox_app.settings
  DJANGO_SECRET_KEY: 1n53cur3K3y
  DJANGO_LOG_LEVEL: WARNING
  POSTGRES_HOST: db
  POSTGRES_USER: redbox-core
  POSTGRES_DB: redbox-core
  POSTGRES_PASSWORD: insecure
  ENVIRONMENT: LOCAL
  USE_STREAMING: False
  COMPRESSION_ENABLED: False
  CONTACT_EMAIL: redbox-copilot@cabinetoffice.gov.uk
  CORE_API_HOST: http://core-api
  CORE_API_PORT: 5002
  EMAIL_BACKEND_TYPE: CONSOLE
  GOV_NOTIFY_API_KEY: f4k3_k3y
  FROM_EMAIL: test@example.com
  GOVUK_NOTIFY_PLAIN_EMAIL_TEMPLATE_ID: example-id
  EMAIL_FILE_PATH: '/app/mail'

permissions:
  contents: read

jobs:
  backend-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.7.0

    - name: Build Containers
      run: |
        mkdir -p data/elastic/
        chmod -R 777 data/
        docker compose up -d --wait core-api worker
        

    - name: Wait 60s for services to be ready
      run: |
        sleep 60

    - name: Test integration with pytest
      run: |
        pip install requests
        pip install pytest
        pip install boto3
        pip install python-jose
        python -m pytest tests

    - name: notify slack failure
      id: slack-failure
      uses: slackapi/slack-github-action@v1.24.0
      if: ${{ failure() && github.event_name == 'schedule' }}
      with:
        channel-id: 'C05D67P6M34'
        payload: |
          {
            "text": "Scheduled Integration Tests Failed",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Scheduled integration tests are failing :alert:"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "logs"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: notify slack pass
      id: slack-pass
      uses: slackapi/slack-github-action@v1.24.0
      if: ${{ success() && github.event_name == 'schedule' }}
      with:
        channel-id: 'C05D67P6M34'
        payload: |
          {
            "text": "Scheduled Integration Tests Passed",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Scheduled integration tests are passing :white_check_mark:"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
